// Code generated by protoc-gen-protonats-ts. DO NOT EDIT.
// source: test.proto

import type { HandlerContext, CallOptions, HandlerOptions } from "@protonats/runtime";
import { ProtoNatsConn, Registration, encode } from "@protonats/runtime";

import { type EchoRequest, type EchoResponse, type GetItemRequest, type Item, type NotifyRequest, type PingRequest, type PingResponse, EchoRequestSchema, EchoResponseSchema, GetItemRequestSchema, ItemSchema, NotifyRequestSchema, PingRequestSchema, PingResponseSchema } from "./test_pb.js";

export class TestServiceClient {
  constructor(private readonly pn: ProtoNatsConn) {}

  async echo(req: EchoRequest, opts?: CallOptions): Promise<EchoResponse> {
    return this.pn.request("testpkg.Echo", req, EchoRequestSchema, EchoResponseSchema, opts);
  }

  async getItem(req: GetItemRequest, opts?: CallOptions): Promise<Item> {
    return this.pn.request(`items.${req.itemId}`, req, GetItemRequestSchema, ItemSchema, opts);
  }

  notify(req: NotifyRequest, opts?: CallOptions): void {
    this.pn.publish("testpkg.Notify", req, NotifyRequestSchema, opts);
  }

  // EmitEvent (JETSTREAM_PUBLISH) is not generated: the TS runtime
  // does not support JetStream; use the nats.js JetStream API directly.

  // ChargeCard (JETSTREAM_TASK) is not generated: the TS runtime
  // does not support JetStream; use the nats.js JetStream API directly.

}

export interface TestServiceHandler {
  echo(ctx: HandlerContext, req: EchoRequest): Promise<EchoResponse>;
  getItem(ctx: HandlerContext, req: GetItemRequest): Promise<Item>;
  notify(ctx: HandlerContext, req: NotifyRequest): Promise<void>;
  // ProcessEvent (JETSTREAM_CONSUME) is not generated: the TS runtime
  // does not support JetStream; use the nats.js JetStream API directly.

  // ChargeCard (JETSTREAM_TASK) is not generated: the TS runtime
  // does not support JetStream; use the nats.js JetStream API directly.

}

export function registerTestServiceHandler(
  pn: ProtoNatsConn,
  handler: TestServiceHandler,
  opts?: HandlerOptions,
): Registration {
  const reg = new Registration();

  reg.addSubscription(
    pn.subscribe(
      "testpkg.TestService.Echo",
      "testpkg.Echo",
      opts?.queueGroup,
      EchoRequestSchema,
      async (ctx, req) => {
        const resp = await handler.echo(ctx, req as EchoRequest);
        return encode(EchoResponseSchema, resp);
      },
    ),
  );

  reg.addSubscription(
    pn.subscribe(
      "testpkg.TestService.GetItem",
      "items.*",
      opts?.queueGroup,
      GetItemRequestSchema,
      async (ctx, req) => {
        const resp = await handler.getItem(ctx, req as GetItemRequest);
        return encode(ItemSchema, resp);
      },
    ),
  );

  reg.addSubscription(
    pn.subscribePublish(
      "testpkg.TestService.Notify",
      "testpkg.Notify",
      opts?.queueGroup,
      NotifyRequestSchema,
      async (ctx, req) => {
        await handler.notify(ctx, req as NotifyRequest);
      },
    ),
  );

  return reg;
}

export class PrefixedServiceClient {
  constructor(private readonly pn: ProtoNatsConn) {}

  async ping(req: PingRequest, opts?: CallOptions): Promise<PingResponse> {
    return this.pn.request("custom.prefix.Ping", req, PingRequestSchema, PingResponseSchema, opts);
  }

}

export interface PrefixedServiceHandler {
  ping(ctx: HandlerContext, req: PingRequest): Promise<PingResponse>;
}

export function registerPrefixedServiceHandler(
  pn: ProtoNatsConn,
  handler: PrefixedServiceHandler,
  opts?: HandlerOptions,
): Registration {
  const reg = new Registration();

  reg.addSubscription(
    pn.subscribe(
      "testpkg.PrefixedService.Ping",
      "custom.prefix.Ping",
      opts?.queueGroup,
      PingRequestSchema,
      async (ctx, req) => {
        const resp = await handler.ping(ctx, req as PingRequest);
        return encode(PingResponseSchema, resp);
      },
    ),
  );

  return reg;
}

