// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protonats/options.proto

package protonats

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodType int32

const (
	MethodType_REQUEST_REPLY     MethodType = 0
	MethodType_PUBLISH           MethodType = 1
	MethodType_JETSTREAM_PUBLISH MethodType = 2
	MethodType_JETSTREAM_CONSUME MethodType = 3
)

// Enum value maps for MethodType.
var (
	MethodType_name = map[int32]string{
		0: "REQUEST_REPLY",
		1: "PUBLISH",
		2: "JETSTREAM_PUBLISH",
		3: "JETSTREAM_CONSUME",
	}
	MethodType_value = map[string]int32{
		"REQUEST_REPLY":     0,
		"PUBLISH":           1,
		"JETSTREAM_PUBLISH": 2,
		"JETSTREAM_CONSUME": 3,
	}
)

func (x MethodType) Enum() *MethodType {
	p := new(MethodType)
	*p = x
	return p
}

func (x MethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_protonats_options_proto_enumTypes[0].Descriptor()
}

func (MethodType) Type() protoreflect.EnumType {
	return &file_protonats_options_proto_enumTypes[0]
}

func (x MethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodType.Descriptor instead.
func (MethodType) EnumDescriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{0}
}

// Service-level options.
type ServiceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subject prefix for all methods. Default: proto package name.
	SubjectPrefix string `protobuf:"bytes,1,opt,name=subject_prefix,json=subjectPrefix,proto3" json:"subject_prefix,omitempty"`
	// Enable NATS micro service discovery.
	Micro bool `protobuf:"varint,2,opt,name=micro,proto3" json:"micro,omitempty"`
	// Service version for micro discovery (semver). Required if micro is true.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Human-readable description for micro discovery.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonats_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protonats_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetSubjectPrefix() string {
	if x != nil {
		return x.SubjectPrefix
	}
	return ""
}

func (x *ServiceOptions) GetMicro() bool {
	if x != nil {
		return x.Micro
	}
	return false
}

func (x *ServiceOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Method-level options.
type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Communication pattern. Default: REQUEST_REPLY.
	Type MethodType `protobuf:"varint,1,opt,name=type,proto3,enum=protonats.MethodType" json:"type,omitempty"`
	// NATS subject override. Supports {field_name} interpolation.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// JetStream stream name. Required for JETSTREAM_PUBLISH / JETSTREAM_CONSUME.
	Stream string `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	// Durable consumer name for JETSTREAM_CONSUME.
	Consumer string `protobuf:"bytes,4,opt,name=consumer,proto3" json:"consumer,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonats_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protonats_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetType() MethodType {
	if x != nil {
		return x.Type
	}
	return MethodType_REQUEST_REPLY
}

func (x *MethodOptions) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MethodOptions) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *MethodOptions) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

// Field-level options.
type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Marks this field as a dynamic NATS subject token.
	SubjectToken bool `protobuf:"varint,1,opt,name=subject_token,json=subjectToken,proto3" json:"subject_token,omitempty"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonats_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protonats_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetSubjectToken() bool {
	if x != nil {
		return x.SubjectToken
	}
	return false
}

// Message-level options.
type MessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv *KVOptions `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonats_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protonats_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{3}
}

func (x *MessageOptions) GetKv() *KVOptions {
	if x != nil {
		return x.Kv
	}
	return nil
}

type KVOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// KV bucket name.
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Key template using {field_name} interpolation.
	KeyTemplate string `protobuf:"bytes,2,opt,name=key_template,json=keyTemplate,proto3" json:"key_template,omitempty"`
}

func (x *KVOptions) Reset() {
	*x = KVOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protonats_options_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVOptions) ProtoMessage() {}

func (x *KVOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protonats_options_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVOptions.ProtoReflect.Descriptor instead.
func (*KVOptions) Descriptor() ([]byte, []int) {
	return file_protonats_options_proto_rawDescGZIP(), []int{4}
}

func (x *KVOptions) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVOptions) GetKeyTemplate() string {
	if x != nil {
		return x.KeyTemplate
	}
	return ""
}

var file_protonats_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         50100,
		Name:          "protonats.service",
		Tag:           "bytes,50100,opt,name=service",
		Filename:      "protonats/options.proto",
	},
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         50100,
		Name:          "protonats.method",
		Tag:           "bytes,50100,opt,name=method",
		Filename:      "protonats/options.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50100,
		Name:          "protonats.field",
		Tag:           "bytes,50100,opt,name=field",
		Filename:      "protonats/options.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         50100,
		Name:          "protonats.message",
		Tag:           "bytes,50100,opt,name=message",
		Filename:      "protonats/options.proto",
	},
}

// Extension fields to descriptor.ServiceOptions.
var (
	// optional protonats.ServiceOptions service = 50100;
	E_Service = &file_protonats_options_proto_extTypes[0]
)

// Extension fields to descriptor.MethodOptions.
var (
	// optional protonats.MethodOptions method = 50100;
	E_Method = &file_protonats_options_proto_extTypes[1]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional protonats.FieldOptions field = 50100;
	E_Field = &file_protonats_options_proto_extTypes[2]
)

// Extension fields to descriptor.MessageOptions.
var (
	// optional protonats.MessageOptions message = 50100;
	E_Message = &file_protonats_options_proto_extTypes[3]
)

var File_protonats_options_proto protoreflect.FileDescriptor

var file_protonats_options_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6e, 0x61, 0x74, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x22, 0x33, 0x0a,
	0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x36, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x4b, 0x56, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x02, 0x6b, 0x76, 0x22, 0x46, 0x0a, 0x09, 0x4b, 0x56,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2a, 0x5a, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x50, 0x4c,
	0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x4a, 0x45, 0x54, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x4a, 0x45, 0x54, 0x53, 0x54,
	0x52, 0x45, 0x41, 0x4d, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x45, 0x10, 0x03, 0x3a, 0x59,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb4, 0x87, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x88, 0x01, 0x01, 0x3a, 0x55, 0x0a, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xb4, 0x87, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x88, 0x01, 0x01,
	0x3a, 0x51, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb4, 0x87, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x88, 0x01, 0x01, 0x3a, 0x59, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xb4, 0x87, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e,
	0x61, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x64,
	0x6f, 0x6d, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protonats_options_proto_rawDescOnce sync.Once
	file_protonats_options_proto_rawDescData = file_protonats_options_proto_rawDesc
)

func file_protonats_options_proto_rawDescGZIP() []byte {
	file_protonats_options_proto_rawDescOnce.Do(func() {
		file_protonats_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_protonats_options_proto_rawDescData)
	})
	return file_protonats_options_proto_rawDescData
}

var file_protonats_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protonats_options_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protonats_options_proto_goTypes = []any{
	(MethodType)(0),                   // 0: protonats.MethodType
	(*ServiceOptions)(nil),            // 1: protonats.ServiceOptions
	(*MethodOptions)(nil),             // 2: protonats.MethodOptions
	(*FieldOptions)(nil),              // 3: protonats.FieldOptions
	(*MessageOptions)(nil),            // 4: protonats.MessageOptions
	(*KVOptions)(nil),                 // 5: protonats.KVOptions
	(*descriptor.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
	(*descriptor.MethodOptions)(nil),  // 7: google.protobuf.MethodOptions
	(*descriptor.FieldOptions)(nil),   // 8: google.protobuf.FieldOptions
	(*descriptor.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
}
var file_protonats_options_proto_depIdxs = []int32{
	0,  // 0: protonats.MethodOptions.type:type_name -> protonats.MethodType
	5,  // 1: protonats.MessageOptions.kv:type_name -> protonats.KVOptions
	6,  // 2: protonats.service:extendee -> google.protobuf.ServiceOptions
	7,  // 3: protonats.method:extendee -> google.protobuf.MethodOptions
	8,  // 4: protonats.field:extendee -> google.protobuf.FieldOptions
	9,  // 5: protonats.message:extendee -> google.protobuf.MessageOptions
	1,  // 6: protonats.service:type_name -> protonats.ServiceOptions
	2,  // 7: protonats.method:type_name -> protonats.MethodOptions
	3,  // 8: protonats.field:type_name -> protonats.FieldOptions
	4,  // 9: protonats.message:type_name -> protonats.MessageOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	6,  // [6:10] is the sub-list for extension type_name
	2,  // [2:6] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protonats_options_proto_init() }
func file_protonats_options_proto_init() {
	if File_protonats_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protonats_options_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonats_options_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonats_options_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonats_options_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protonats_options_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*KVOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protonats_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_protonats_options_proto_goTypes,
		DependencyIndexes: file_protonats_options_proto_depIdxs,
		EnumInfos:         file_protonats_options_proto_enumTypes,
		MessageInfos:      file_protonats_options_proto_msgTypes,
		ExtensionInfos:    file_protonats_options_proto_extTypes,
	}.Build()
	File_protonats_options_proto = out.File
	file_protonats_options_proto_rawDesc = nil
	file_protonats_options_proto_goTypes = nil
	file_protonats_options_proto_depIdxs = nil
}
