package gents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mudomi/protonats/internal/gen"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestGenerateFile(t *testing.T) {
	// Build a CodeGeneratorRequest from the test proto descriptor.
	desc := buildTestDescriptor(t)
	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile:      []*descriptorpb.FileDescriptorProto{desc},
	}

	opts := protogen.Options{}
	plugin, err := opts.New(req)
	if err != nil {
		t.Fatal(err)
	}

	for _, file := range plugin.Files {
		if file.Generate {
			GenerateFile(plugin, file)
		}
	}

	resp := plugin.Response()
	if resp.Error != nil {
		t.Fatalf("plugin error: %s", resp.GetError())
	}

	if len(resp.File) == 0 {
		t.Fatal("no files generated")
	}

	generated := resp.File[0].GetContent()

	// Verify key patterns are present in the generated output.
	checks := []string{
		"// Code generated by protoc-gen-protonats-ts. DO NOT EDIT.",
		"import type { HandlerContext, CallOptions, HandlerOptions } from \"@protonats/runtime\";",
		"import { ProtoNatsConn, Registration, encode } from \"@protonats/runtime\";",

		// TestService client
		"export class TestServiceClient {",
		"async echo(req: EchoRequest, opts?: CallOptions): Promise<EchoResponse>",
		"async getItem(req: GetItemRequest, opts?: CallOptions): Promise<Item>",
		"`items.${req.itemId}`",
		"notify(req: NotifyRequest, opts?: CallOptions): void",
		"emitEvent(req: EventPayload, opts?: CallOptions): void",

		// TestService handler
		"export interface TestServiceHandler {",
		"echo(ctx: HandlerContext, req: EchoRequest): Promise<EchoResponse>;",
		"getItem(ctx: HandlerContext, req: GetItemRequest): Promise<Item>;",
		"notify(ctx: HandlerContext, req: NotifyRequest): Promise<void>;",
		"processEvent(ctx: HandlerContext, req: EventPayload): Promise<void>;",

		// TestService register
		"export function registerTestServiceHandler(",

		// PrefixedService uses custom prefix
		"export class PrefixedServiceClient {",
		`"custom.prefix.Ping"`,
		"export interface PrefixedServiceHandler {",
		"export function registerPrefixedServiceHandler(",

		// _pb.js import
		`from "./test_pb.js"`,
	}

	for _, check := range checks {
		if !strings.Contains(generated, check) {
			t.Errorf("generated output missing: %s", check)
		}
	}

	// Write snapshot for manual inspection.
	snapshotDir := filepath.Join("testdata", "snapshots")
	_ = os.MkdirAll(snapshotDir, 0o755)
	snapshotPath := filepath.Join(snapshotDir, "test_protonats.ts")

	existing, readErr := os.ReadFile(snapshotPath)
	if readErr == nil && string(existing) == generated {
		return // snapshot matches
	}

	if os.Getenv("UPDATE_SNAPSHOTS") == "1" || readErr != nil {
		if err := os.WriteFile(snapshotPath, []byte(generated), 0o644); err != nil {
			t.Fatalf("write snapshot: %v", err)
		}
		if readErr != nil {
			t.Logf("created snapshot: %s", snapshotPath)
		} else {
			t.Logf("updated snapshot: %s", snapshotPath)
		}
		return
	}

	t.Errorf("snapshot mismatch. Run with UPDATE_SNAPSHOTS=1 to update.\n\nGot:\n%s", generated)
}

// buildTestDescriptor constructs a FileDescriptorProto matching internal/gen/testdata/test.proto.
func buildTestDescriptor(t *testing.T) *descriptorpb.FileDescriptorProto {
	t.Helper()

	pkg := "testpkg"
	syntax := "proto3"

	// Method option helpers
	reqReply := methodOpts(0, "")       // REQUEST_REPLY
	publish := methodOpts(1, "")        // PUBLISH
	jsPublish := methodOpts(2, "")      // JETSTREAM_PUBLISH
	jsConsume := methodOpts(3, "")      // JETSTREAM_CONSUME
	customSubj := methodOpts(0, "items.{item_id}")

	svcOpts := serviceOpts("custom.prefix")

	return &descriptorpb.FileDescriptorProto{
		Name:    strp("test.proto"),
		Package: &pkg,
		Syntax:  &syntax,
		Options: &descriptorpb.FileOptions{
			GoPackage: strp("github.com/mudomi/protonats/internal/gents/testdata/gen;testgen"),
		},
		MessageType: []*descriptorpb.DescriptorProto{
			msgDesc("EchoRequest", "message"),
			msgDesc("EchoResponse", "message"),
			msgDesc("GetItemRequest", "item_id"),
			msgDesc("Item", "item_id", "name"),
			msgDesc("NotifyRequest", "text"),
			msgDesc("NotifyResponse"),
			msgDesc("EventPayload", "event_id", "data"),
			msgDesc("EmitEventResponse"),
			msgDesc("ProcessEventResponse"),
			msgDesc("PingRequest"),
			msgDesc("PingResponse", "pong"),
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: strp("TestService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					methodDesc("Echo", ".testpkg.EchoRequest", ".testpkg.EchoResponse", reqReply),
					methodDesc("GetItem", ".testpkg.GetItemRequest", ".testpkg.Item", customSubj),
					methodDesc("Notify", ".testpkg.NotifyRequest", ".testpkg.NotifyResponse", publish),
					methodDesc("EmitEvent", ".testpkg.EventPayload", ".testpkg.EmitEventResponse", jsPublish),
					methodDesc("ProcessEvent", ".testpkg.EventPayload", ".testpkg.ProcessEventResponse", jsConsume),
				},
			},
			{
				Name:    strp("PrefixedService"),
				Options: svcOpts,
				Method: []*descriptorpb.MethodDescriptorProto{
					methodDesc("Ping", ".testpkg.PingRequest", ".testpkg.PingResponse", reqReply),
				},
			},
		},
	}
}

func strp(s string) *string { return &s }

func msgDesc(name string, fields ...string) *descriptorpb.DescriptorProto {
	d := &descriptorpb.DescriptorProto{Name: strp(name)}
	for i, f := range fields {
		num := int32(i + 1)
		typ := descriptorpb.FieldDescriptorProto_TYPE_STRING
		d.Field = append(d.Field, &descriptorpb.FieldDescriptorProto{
			Name:   strp(f),
			Number: &num,
			Type:   &typ,
		})
	}
	return d
}

func methodDesc(name, input, output string, opts *descriptorpb.MethodOptions) *descriptorpb.MethodDescriptorProto {
	return &descriptorpb.MethodDescriptorProto{
		Name:       strp(name),
		InputType:  strp(input),
		OutputType: strp(output),
		Options:    opts,
	}
}

func methodOpts(methodType int32, subject string) *descriptorpb.MethodOptions {
	mo := &gen.MethodOptions{
		Type:    gen.MethodType(methodType),
		Subject: subject,
	}
	return encodeMethodOptions(mo)
}

func serviceOpts(prefix string) *descriptorpb.ServiceOptions {
	so := &gen.ServiceOptions{
		SubjectPrefix: prefix,
	}
	return encodeServiceOptions(so)
}

// encodeMethodOptions creates a MethodOptions descriptor with the protonats extension.
func encodeMethodOptions(mo *gen.MethodOptions) *descriptorpb.MethodOptions {
	opts := &descriptorpb.MethodOptions{}
	// Encode as wire bytes for the extension field 50100.
	var extData []byte
	if mo.Type != 0 {
		extData = append(extData, encodeVarintField(1, uint64(mo.Type))...)
	}
	if mo.Subject != "" {
		extData = append(extData, encodeLenField(2, []byte(mo.Subject))...)
	}
	if mo.Stream != "" {
		extData = append(extData, encodeLenField(3, []byte(mo.Stream))...)
	}
	if mo.Consumer != "" {
		extData = append(extData, encodeLenField(4, []byte(mo.Consumer))...)
	}
	if len(extData) > 0 {
		raw, _ := proto.Marshal(opts)
		raw = append(raw, encodeLenField(50100, extData)...)
		proto.Unmarshal(raw, opts)
	}
	return opts
}

func encodeServiceOptions(so *gen.ServiceOptions) *descriptorpb.ServiceOptions {
	opts := &descriptorpb.ServiceOptions{}
	var extData []byte
	if so.SubjectPrefix != "" {
		extData = append(extData, encodeLenField(1, []byte(so.SubjectPrefix))...)
	}
	if len(extData) > 0 {
		raw, _ := proto.Marshal(opts)
		raw = append(raw, encodeLenField(50100, extData)...)
		proto.Unmarshal(raw, opts)
	}
	return opts
}

func encodeVarintField(fieldNum uint32, val uint64) []byte {
	tag := (fieldNum << 3) | 0
	b := appendVarint(nil, uint64(tag))
	b = appendVarint(b, val)
	return b
}

func encodeLenField(fieldNum uint32, data []byte) []byte {
	tag := (fieldNum << 3) | 2
	b := appendVarint(nil, uint64(tag))
	b = appendVarint(b, uint64(len(data)))
	b = append(b, data...)
	return b
}

func appendVarint(b []byte, v uint64) []byte {
	for v >= 0x80 {
		b = append(b, byte(v)|0x80)
		v >>= 7
	}
	return append(b, byte(v))
}
