package gents

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	protonats "github.com/mudomi/protonats"
	"github.com/mudomi/protonats/internal/gen"
)

// GenerateFile produces a _protonats.ts file for each proto file with services.
func GenerateFile(plugin *protogen.Plugin, file *protogen.File) error {
	if len(file.Services) == 0 {
		return nil
	}
	if err := gen.ValidateFile(file); err != nil {
		return err
	}

	filename := file.GeneratedFilenamePrefix + "_protonats.ts"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	pbImportPath := "./" + strings.TrimSuffix(filepath.Base(file.GeneratedFilenamePrefix), filepath.Ext(file.GeneratedFilenamePrefix)) + "_pb.js"

	// Collect all message types we need to import from the _pb.ts file.
	types, schemas := collectImports(file)

	g.P("// Code generated by protoc-gen-protonats-ts. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("import type { HandlerContext, CallOptions, HandlerOptions } from \"@protonats/runtime\";")
	g.P("import { ProtoNatsConn, Registration, encode } from \"@protonats/runtime\";")
	g.P()

	if len(types) > 0 || len(schemas) > 0 {
		var imports []string
		for _, t := range types {
			imports = append(imports, "type "+t)
		}
		imports = append(imports, schemas...)
		g.P("import { ", strings.Join(imports, ", "), " } from \"", pbImportPath, "\";")
		g.P()
	}

	for _, svc := range file.Services {
		prefix := gen.SubjectPrefix(file, svc)
		generateClient(g, svc, prefix)
		generateHandlerInterface(g, svc)
		generateRegister(g, svc, prefix)
	}
	return nil
}

func collectImports(file *protogen.File) (types []string, schemas []string) {
	seen := map[string]bool{}
	add := func(name string) {
		if !seen[name] {
			seen[name] = true
			types = append(types, name)
			schemas = append(schemas, name+"Schema")
		}
	}

	for _, svc := range file.Services {
		for _, m := range svc.Methods {
			switch gen.MethodTypeOf(m) {
			case protonats.MethodType_REQUEST_REPLY:
				add(string(m.Input.Desc.Name()))
				add(string(m.Output.Desc.Name()))
			case protonats.MethodType_PUBLISH:
				add(string(m.Input.Desc.Name()))
			}
		}
	}
	return
}

// jetStreamNotice explains why a method is absent from the generated TS code.
func jetStreamNotice(g *protogen.GeneratedFile, m *protogen.Method) {
	g.P("  // ", m.GoName, " (", gen.MethodTypeOf(m), ") is not generated: the TS runtime")
	g.P("  // does not support JetStream; use the nats.js JetStream API directly.")
	g.P()
}

// ── Client ──

func generateClient(g *protogen.GeneratedFile, svc *protogen.Service, prefix string) {
	name := svc.GoName

	g.P("export class ", name, "Client {")
	g.P("  constructor(private readonly pn: ProtoNatsConn) {}")
	g.P()

	for _, m := range svc.Methods {
		subject := gen.MethodSubject(prefix, m)
		tokens, _ := gen.TokenFields(m, subject) // validated in GenerateFile
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)
		subjectExpr := subjectTemplateLiteral(subject, tokens)

		switch gen.MethodTypeOf(m) {
		case protonats.MethodType_REQUEST_REPLY:
			outName := string(m.Output.Desc.Name())
			g.P("  async ", tsMethod, "(req: ", inName, ", opts?: CallOptions): Promise<", outName, "> {")
			g.P("    return this.pn.request(", subjectExpr, ", req, ", inName, "Schema, ", outName, "Schema, opts);")
			g.P("  }")
			g.P()

		case protonats.MethodType_PUBLISH:
			g.P("  ", tsMethod, "(req: ", inName, ", opts?: CallOptions): void {")
			g.P("    this.pn.publish(", subjectExpr, ", req, ", inName, "Schema, opts);")
			g.P("  }")
			g.P()

		case protonats.MethodType_JETSTREAM_PUBLISH, protonats.MethodType_JETSTREAM_TASK:
			jetStreamNotice(g, m)

		case protonats.MethodType_JETSTREAM_CONSUME:
			// No client for consumers.
		}
	}

	g.P("}")
	g.P()
}

// ── Handler interface ──

func generateHandlerInterface(g *protogen.GeneratedFile, svc *protogen.Service) {
	name := svc.GoName

	g.P("export interface ", name, "Handler {")
	for _, m := range svc.Methods {
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)

		switch gen.MethodTypeOf(m) {
		case protonats.MethodType_REQUEST_REPLY:
			outName := string(m.Output.Desc.Name())
			g.P("  ", tsMethod, "(ctx: HandlerContext, req: ", inName, "): Promise<", outName, ">;")
		case protonats.MethodType_PUBLISH:
			g.P("  ", tsMethod, "(ctx: HandlerContext, req: ", inName, "): Promise<void>;")
		case protonats.MethodType_JETSTREAM_CONSUME, protonats.MethodType_JETSTREAM_TASK:
			jetStreamNotice(g, m)
		}
	}
	g.P("}")
	g.P()
}

// ── Register ──

func generateRegister(g *protogen.GeneratedFile, svc *protogen.Service, prefix string) {
	name := svc.GoName

	g.P("export function register", name, "Handler(")
	g.P("  pn: ProtoNatsConn,")
	g.P("  handler: ", name, "Handler,")
	g.P("  opts?: HandlerOptions,")
	g.P("): Registration {")
	g.P("  const reg = new Registration();")
	g.P()

	for _, m := range svc.Methods {
		subject := gen.MethodSubject(prefix, m)
		subSubject := gen.SubscribeSubject(subject)
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)

		switch gen.MethodTypeOf(m) {
		case protonats.MethodType_REQUEST_REPLY:
			outName := string(m.Output.Desc.Name())
			g.P("  reg.addSubscription(")
			g.P("    pn.subscribe(")
			g.P(fmt.Sprintf("      %q,", string(m.Desc.FullName())))
			g.P(fmt.Sprintf("      %q,", subSubject))
			g.P("      opts?.queueGroup,")
			g.P("      ", inName, "Schema,")
			g.P("      async (ctx, req) => {")
			g.P("        const resp = await handler.", tsMethod, "(ctx, req as ", inName, ");")
			g.P("        return encode(", outName, "Schema, resp);")
			g.P("      },")
			g.P("    ),")
			g.P("  );")
			g.P()

		case protonats.MethodType_PUBLISH:
			g.P("  reg.addSubscription(")
			g.P("    pn.subscribePublish(")
			g.P(fmt.Sprintf("      %q,", string(m.Desc.FullName())))
			g.P(fmt.Sprintf("      %q,", subSubject))
			g.P("      opts?.queueGroup,")
			g.P("      ", inName, "Schema,")
			g.P("      async (ctx, req) => {")
			g.P("        await handler.", tsMethod, "(ctx, req as ", inName, ");")
			g.P("      },")
			g.P("    ),")
			g.P("  );")
			g.P()
		}
	}

	g.P("  return reg;")
	g.P("}")
	g.P()
}
