package gents_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mudomi/protonats/internal/gentest"
	"github.com/mudomi/protonats/internal/gents"
)

func TestGenerateFile(t *testing.T) {
	plugin := gentest.NewPlugin(t)
	file := gentest.TestFile(t, plugin)

	if err := gents.GenerateFile(plugin, file); err != nil {
		t.Fatal(err)
	}

	resp := plugin.Response()
	if resp.Error != nil {
		t.Fatalf("plugin error: %s", resp.GetError())
	}
	if len(resp.File) != 1 {
		t.Fatalf("generated %d files, want 1", len(resp.File))
	}
	generated := resp.File[0].GetContent()

	// Verify key patterns are present in the generated output.
	checks := []string{
		"// Code generated by protoc-gen-protonats-ts. DO NOT EDIT.",
		"import type { HandlerContext, CallOptions, HandlerOptions } from \"@protonats/runtime\";",
		"import { ProtoNatsConn, Registration, encode } from \"@protonats/runtime\";",

		// TestService client
		"export class TestServiceClient {",
		"async echo(req: EchoRequest, opts?: CallOptions): Promise<EchoResponse>",
		"async getItem(req: GetItemRequest, opts?: CallOptions): Promise<Item>",
		"`items.${req.itemId}`",
		"notify(req: NotifyRequest, opts?: CallOptions): void",

		// JetStream methods are skipped with an explanatory comment.
		"// EmitEvent (JETSTREAM_PUBLISH) is not generated",
		"// ProcessEvent (JETSTREAM_CONSUME) is not generated",

		// TestService handler
		"export interface TestServiceHandler {",
		"echo(ctx: HandlerContext, req: EchoRequest): Promise<EchoResponse>;",
		"notify(ctx: HandlerContext, req: NotifyRequest): Promise<void>;",

		// TestService register
		"export function registerTestServiceHandler(",

		// PrefixedService uses custom prefix
		"export class PrefixedServiceClient {",
		`"custom.prefix.Ping"`,

		// _pb.js import
		`from "./test_pb.js"`,
	}
	for _, check := range checks {
		if !strings.Contains(generated, check) {
			t.Errorf("generated output missing: %s", check)
		}
	}

	// JetStream types must not be imported or referenced in real code.
	for _, absent := range []string{"emitEvent(", "processEvent(ctx"} {
		if strings.Contains(generated, absent) {
			t.Errorf("generated output should not contain: %s", absent)
		}
	}

	compareSnapshot(t, generated)
}

func compareSnapshot(t *testing.T, generated string) {
	t.Helper()
	snapshotPath := filepath.Join("testdata", "snapshots", "test_protonats.ts")

	existing, readErr := os.ReadFile(snapshotPath)
	if readErr == nil && string(existing) == generated {
		return
	}

	if os.Getenv("UPDATE_SNAPSHOTS") == "1" || readErr != nil {
		if err := os.WriteFile(snapshotPath, []byte(generated), 0o644); err != nil {
			t.Fatalf("write snapshot: %v", err)
		}
		t.Logf("wrote snapshot: %s", snapshotPath)
		return
	}

	t.Errorf("snapshot mismatch. Run with UPDATE_SNAPSHOTS=1 to update.\n\nGot:\n%s", generated)
}
