package gents

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"

	"github.com/mudomi/protonats/internal/gen"
)

// GenerateFile produces a _protonats.ts file for each proto file with services.
func GenerateFile(plugin *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_protonats.ts"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	pbImportPath := "./" + strings.TrimSuffix(filepath.Base(file.GeneratedFilenamePrefix), filepath.Ext(file.GeneratedFilenamePrefix)) + "_pb.js"

	// Collect all message types we need to import from the _pb.ts file.
	types, schemas := collectImports(file)

	g.P("// Code generated by protoc-gen-protonats-ts. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("import type { HandlerContext, CallOptions, HandlerOptions } from \"@protonats/runtime\";")
	g.P("import { ProtoNatsConn, Registration, encode } from \"@protonats/runtime\";")
	g.P()

	if len(types) > 0 || len(schemas) > 0 {
		var imports []string
		for _, t := range types {
			imports = append(imports, "type "+t)
		}
		imports = append(imports, schemas...)
		g.P("import { ", strings.Join(imports, ", "), " } from \"", pbImportPath, "\";")
		g.P()
	}

	for _, svc := range file.Services {
		prefix := resolveSubjectPrefix(file, svc)
		generateClient(g, svc, prefix)
		generateHandlerInterface(g, svc)
		generateRegister(g, svc, prefix)
	}
}

func collectImports(file *protogen.File) (types []string, schemas []string) {
	seen := map[string]bool{}
	for _, svc := range file.Services {
		for _, m := range svc.Methods {
			inName := string(m.Input.Desc.Name())
			outName := string(m.Output.Desc.Name())
			mt := methodType(m)

			if !seen[inName] {
				seen[inName] = true
				types = append(types, inName)
				schemas = append(schemas, inName+"Schema")
			}

			if mt == gen.MethodTypeRequestReply && !seen[outName] {
				seen[outName] = true
				types = append(types, outName)
				schemas = append(schemas, outName+"Schema")
			}
		}
	}
	return
}

func resolveSubjectPrefix(file *protogen.File, svc *protogen.Service) string {
	if raw, ok := svc.Desc.Options().(*descriptorpb.ServiceOptions); ok {
		if opts := gen.GetServiceOptions(raw); opts != nil && opts.SubjectPrefix != "" {
			return opts.SubjectPrefix
		}
	}
	return string(file.Desc.Package())
}

func methodType(m *protogen.Method) gen.MethodType {
	if raw, ok := m.Desc.Options().(*descriptorpb.MethodOptions); ok {
		if opts := gen.GetMethodOptions(raw); opts != nil {
			return opts.Type
		}
	}
	return gen.MethodTypeRequestReply
}

func methodSubject(prefix string, m *protogen.Method) string {
	if raw, ok := m.Desc.Options().(*descriptorpb.MethodOptions); ok {
		if opts := gen.GetMethodOptions(raw); opts != nil && opts.Subject != "" {
			return opts.Subject
		}
	}
	return prefix + "." + string(m.Desc.Name())
}

// ── Client ──

func generateClient(g *protogen.GeneratedFile, svc *protogen.Service, prefix string) {
	name := svc.GoName

	g.P("export class ", name, "Client {")
	g.P("  constructor(private readonly pn: ProtoNatsConn) {}")
	g.P()

	for _, m := range svc.Methods {
		mt := methodType(m)
		subject := methodSubject(prefix, m)
		tokens := subjectTemplateTokens(subject)
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)
		subjectExpr := subjectTemplateLiteral(subject, tokens)

		switch mt {
		case gen.MethodTypeRequestReply:
			outName := string(m.Output.Desc.Name())
			g.P("  async ", tsMethod, "(req: ", inName, ", opts?: CallOptions): Promise<", outName, "> {")
			g.P("    return this.pn.request(", subjectExpr, ", req, ", inName, "Schema, ", outName, "Schema, opts);")
			g.P("  }")
			g.P()

		case gen.MethodTypePublish, gen.MethodTypeJetstreamPublish:
			g.P("  ", tsMethod, "(req: ", inName, ", opts?: CallOptions): void {")
			g.P("    this.pn.publish(", subjectExpr, ", req, ", inName, "Schema, opts);")
			g.P("  }")
			g.P()

		case gen.MethodTypeJetstreamConsume:
			// No client method for consumers.
		}
	}

	g.P("}")
	g.P()
}

// ── Handler interface ──

func generateHandlerInterface(g *protogen.GeneratedFile, svc *protogen.Service) {
	name := svc.GoName

	g.P("export interface ", name, "Handler {")
	for _, m := range svc.Methods {
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)

		switch methodType(m) {
		case gen.MethodTypeRequestReply:
			outName := string(m.Output.Desc.Name())
			g.P("  ", tsMethod, "(ctx: HandlerContext, req: ", inName, "): Promise<", outName, ">;")
		case gen.MethodTypePublish:
			g.P("  ", tsMethod, "(ctx: HandlerContext, req: ", inName, "): Promise<void>;")
		case gen.MethodTypeJetstreamConsume:
			g.P("  ", tsMethod, "(ctx: HandlerContext, req: ", inName, "): Promise<void>;")
		}
	}
	g.P("}")
	g.P()
}

// ── Register ──

func generateRegister(g *protogen.GeneratedFile, svc *protogen.Service, prefix string) {
	name := svc.GoName

	g.P("export function register", name, "Handler(")
	g.P("  pn: ProtoNatsConn,")
	g.P("  handler: ", name, "Handler,")
	g.P("  opts?: HandlerOptions,")
	g.P("): Registration {")
	g.P("  const reg = new Registration();")
	g.P()

	for _, m := range svc.Methods {
		mt := methodType(m)
		subject := methodSubject(prefix, m)
		subSubject := subscribeSubject(subject)
		inName := string(m.Input.Desc.Name())
		tsMethod := pascalToCamel(m.GoName)
		outName := string(m.Output.Desc.Name())

		switch mt {
		case gen.MethodTypeRequestReply:
			g.P("  reg.addSubscription(")
			g.P("    pn.subscribe(")
			g.P(fmt.Sprintf("      %q,", subSubject))
			g.P("      opts?.queueGroup,")
			g.P("      ", inName, "Schema,")
			g.P("      async (ctx, req) => {")
			g.P("        const resp = await handler.", tsMethod, "(ctx, req as ", inName, ");")
			g.P("        return encode(", outName, "Schema, resp);")
			g.P("      },")
			g.P("    ),")
			g.P("  );")
			g.P()

		case gen.MethodTypePublish:
			g.P("  reg.addSubscription(")
			g.P("    pn.subscribePublish(")
			g.P(fmt.Sprintf("      %q,", subSubject))
			g.P("      opts?.queueGroup,")
			g.P("      ", inName, "Schema,")
			g.P("      async (ctx, req) => {")
			g.P("        await handler.", tsMethod, "(ctx, req as ", inName, ");")
			g.P("      },")
			g.P("    ),")
			g.P("  );")
			g.P()
		}
	}

	g.P("  return reg;")
	g.P("}")
	g.P()
}
